title: this is FILTHY
description: >
  Filthy: A word originating in Seattle meaning dope, tight or cool

# We love at, design, fashion and music. We live in Seattle but we work in the global context.

baseurl: ""
url: "filthy.cc"
paginate:	5 # The number of posts to show per page on your homepage
name: "this is FILTHY"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
